### ISSUE TITLE
foobar2000 1.3.14

### ISSUE THREAD

**Issue by welwood08** [niks255/ChocolateyPackages#1]
Hi, I notice the most recent update has been stuck in moderation for a couple of months now and thought I'd mention an alternative solution that doesn't seem to have been discussed (at least that I can see, you might have considered it already).

Embed the installer into the package. This is one of the solutions [officially recommended when FossHub requested to be removed from packages](https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub#option-2---embed-if-software-vendors-license-allows-recommended). As far as I can tell, [fb2k's license](https://www.foobar2000.org/license) is quite clear in allowing exactly this kind of redistribution.

Hope that helps to keep this package simple while fulfilling the review's PS v2 compatibility requirement and ensuring working version history in the future.

**Comment by niks255** [comment]
Not a bad idea actually, would be easier than all these damn hacks to extract links.
Accepted, I will do it right now.
