### ISSUE TITLE
FYI - AU will put your README.md in package description

### ISSUE THREAD

**Issue by majkinetor** [niks255/ChocolateyPackages#2]
In next version of AU there is automatic README.md 2 package description: https://github.com/majkinetor/au#automatic-package-description-from-readmemd

Your README.md in its current state will replace current descriptions. You should either:

- Update them with actual description from nuspec (first 2 lines are ignored)
- delete them
- add `-NoReadme` to `update` call (or set `$au_NoReadme` = $true)

**Comment by niks255** [comment]
Pull requests are welcome

**Comment by majkinetor** [comment]
It was just info, no need to do anything if you don't want to but you could just rename readme.md to something else.

**Comment by niks255** [comment]
No problem, I don't even need it
